java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 1
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 2
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 3
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 4
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 5
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 6
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 7
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 8
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 9
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 10
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 11
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 12
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 13
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 14
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 15
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 16
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 17
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 18
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 19
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 20
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 21
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 22
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 23
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 24
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 25
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 26
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 27
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 28
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 29
java -jar D:\Documents\Computer\TopCoder\Planarity\Visualizer.jar -exec D:\Documents\Computer\TopCoder\Planarity\v4.3.exe -seed 30
