java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 1 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 2 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 3 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 4 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 5 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 6 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 7 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 8 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 9 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 10 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 11 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 12 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 13 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 14 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 15 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 16 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 17 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 18 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 19 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 20 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 21 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 22 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 23 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 24 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 25 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 26 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 27 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 28 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 29 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 30 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 31 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 32 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 33 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 34 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 35 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 36 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 37 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 38 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 39 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 40 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 41 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 42 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 43 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 44 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 45 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 46 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 47 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 48 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 49 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 50 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 51 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 52 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 53 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 54 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 55 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 56 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 57 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 58 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 59 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 60 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 61 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 62 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 63 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 64 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 65 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 66 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 67 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 68 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 69 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 70 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 71 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 72 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 73 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 74 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 75 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 76 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 77 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 78 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 79 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 80 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 81 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 82 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 83 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 84 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 85 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 86 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 87 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 88 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 89 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 90 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 91 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 92 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 93 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 94 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 95 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 96 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 97 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 98 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 99 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 100 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 101 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 102 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 103 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 104 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 105 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 106 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 107 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 108 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 109 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 110 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 111 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 112 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 113 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 114 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 115 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 116 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 117 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 118 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 119 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 120 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 121 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 122 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 123 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 124 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 125 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 126 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 127 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 128 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 129 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 130 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 131 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 132 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 133 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 134 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 135 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 136 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 137 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 138 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 139 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 140 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 141 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 142 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 143 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 144 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 145 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 146 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 147 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 148 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 149 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 150 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 151 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 152 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 153 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 154 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 155 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 156 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 157 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 158 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 159 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 160 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 161 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 162 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 163 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 164 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 165 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 166 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 167 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 168 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 169 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 170 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 171 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 172 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 173 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 174 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 175 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 176 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 177 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 178 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 179 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 180 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 181 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 182 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 183 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 184 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 185 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 186 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 187 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 188 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 189 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 190 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 191 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 192 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 193 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 194 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 195 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 196 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 197 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 198 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 199 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 200 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 201 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 202 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 203 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 204 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 205 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 206 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 207 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 208 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 209 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 210 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 211 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 212 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 213 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 214 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 215 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 216 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 217 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 218 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 219 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 220 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 221 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 222 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 223 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 224 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 225 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 226 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 227 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 228 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 229 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 230 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 231 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 232 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 233 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 234 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 235 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 236 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 237 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 238 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 239 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 240 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 241 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 242 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 243 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 244 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 245 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 246 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 247 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 248 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 249 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 250 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 251 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 252 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 253 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 254 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 255 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 256 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 257 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 258 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 259 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 260 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 261 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 262 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 263 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 264 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 265 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 266 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 267 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 268 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 269 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 270 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 271 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 272 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 273 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 274 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 275 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 276 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 277 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 278 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 279 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 280 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 281 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 282 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 283 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 284 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 285 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 286 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 287 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 288 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 289 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 290 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 291 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 292 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 293 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 294 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 295 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 296 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 297 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 298 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 299 -novis
java -jar D:\Documents\Computer\TopCoder\BookSelection\BookSelectionVis.jar -exec D:\Documents\Computer\TopCoder\BookSelection\v7.2.exe -seed 300 -novis
