java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 1 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 2 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 3 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 4 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 5 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 6 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 7 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 8 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 9 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 10 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 11 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 12 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 13 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 14 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 15 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 16 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 17 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 18 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 19 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 20 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 21 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 22 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 23 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 24 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 25 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 26 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 27 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 28 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 29 -novis
java -jar D:\Documents\Computer\TopCoder\CellularAutomaton\Visualizer.jar -exec D:\Documents\Computer\TopCoder\CellularAutomaton\v2.2.exe -seed 30 -novis
